# Generated by Django 3.1.3 on 2021-01-12 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_sendemail_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sendemail',
            name='description',
            field=models.TextField(),
        ),
    ]
