# Generated by Django 3.1.1 on 2021-01-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20210112_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='sendemail',
            name='phone',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
